### PR TITLE
interactive list

### PR DESCRIPTION
**Pull request by mrEckendonk**
Hi 👋 Codereviewer!

In this exercise I had to:

✅ Add a new JavaScript file and import it as a module:
- it will contain methods related to the status updates (completed: true/false).

✅Add event listener to the checkbox (change).
✅Update items object's value for completed key upon user actions.
✅Implement a function for the "Clear all completed" button (use filter() method).
✅Store the updated array of items in local storage, so the user gets the correct list values after the page reloads.

### CODE REVIEW

**Review by CollinsTatang — CHANGES_REQUESTED** [review]
Hi @mrEckendonk , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] Your app compiles successfully but the app doesn't work on my end, please try to run your project locally again and check the bug stopping it. 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mrEckendonk** [comment]
Hi @CollinsTatang 

I just wrote a message on slack to you. Can you please have a look?

**Comment by mrEckendonk** [comment]
## Hi 👋 other codereviewer,

It seems that the previous code reviewer could not run my app on his machine. On my windows 11 machine if I run `npn run start` it works fine. 

I made a zoom video that you can see the app working. https://www.loom.com/share/024087bbe19c425fa64a715d373d41b2

You can also use the link from netlify to test the app : 
https://deploy-preview-3--todo-today-eckendonk.netlify.app

Please, if you run into the same issue, set this Code Review to "INVALID" so that my only 3 attempts to get my project not being wasted because the project did not run on your local machine.

Thanks for reading!

**Review by AnselemOdims — APPROVED** [review]
### Hi  @mrEckendonk 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
